config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/views/partial/_footer.html.erb
<nav class="navbar navbar-expand navbar-light bg-light mt-auto">
  <div class="nav navbar-nav">
    <% if logged_in? %>
    <p class="nav-item nav-link">
      <%= link_to "投稿", "#", class: "nav-link" %>
    </p>
    <% end %>
    <p class="nav-item nav-link">
      <%= link_to "利用規約", contact_path, class: "nav-link" %>
    </p>
  </div>
</nav>

app/views/partial/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-light bg-light">
    <%= link_to "", root_path, class: "navbar__brand navbar__mainLogo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <% if logged_in? %>
        <li class="nav-item">
          <%= link_to "プロフィールページ", current_user, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "プロフィール編集", edit_user_path(current_user), class: "nav-link" %>
        </li>
        <li>
          <%= link_to "ユーザー情報", users_path, class: "nav-link" %>
        </li>
        <li>
          <%= link_to "ログアウト", logout_path, method: :delete, class: "nav-link" %>
        </li>
        <li class="search-nav">
          <%= form_tag(root_path, method: :get) do %>
            <div class="input-group">
              <%= search_field_tag "q", params[:q], class: "form-control", placeholder: "キーワード検索" %>
              <span class="input-group-btn">
                <%= submit_tag "検索", class: "btn btn-default" %>
              </span>
            </div>
          <% end %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to "新規登録", signup_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログイン", login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Facebookでログイン", "/auth/facebook", class: "nav-link" %>
        </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>